export interface Page<T> { items: T[]; page: number; page_size: number; total: number; pages: number }
export interface InstitutionRef { id: string; slug: string; official_name: string }
export interface EvidenceRef { id: string; title: string; locator: string; observed_at: string; source_name: string; source_url: string; official_source: boolean }
export interface AuthoritySummary { appointment_id: string; person_id: string; public_name: string; position: string; appointment_status: string }
export interface TransparencySummary { assessment_id: string; assessment_date: string; methodology_version: string; normalized_score: number; coverage_percentage: number; maturity_status: string }
export interface ExecutiveSummary { total_institutions: number; total_active_institutions: number; total_ministries: number; presidency_present: boolean; vice_presidency_present: boolean; total_current_authorities: number; total_relationships: number; institutions_with_transparency_assessment: number; institutions_with_complete_assessment: number; institutions_with_partial_assessment: number; latest_data_update: string | null; methodology_versions: string[]; ranking_enabled: false; data_scope: string; limitations: string[] }
export interface InstitutionListItem { id: string; slug: string; official_name: string; short_name: string | null; institution_type: string; status: string; parent_institution: InstitutionRef | null; official_website: string | null; current_authority_summary: AuthoritySummary | null; latest_transparency_summary: TransparencySummary | null; source_count: number; last_verified_at: string | null }
export interface LegalDocument { id: string; norm_type: string; number: string; date: string | null; title: string; url: string | null; located: boolean; searchable: boolean | null; source: EvidenceRef; observations: string | null; limitations: string[] }
export interface RelationshipItem { id: string; direction: "incoming" | "outgoing"; source_institution: InstitutionRef; target_institution: InstitutionRef; relationship_type: string; valid_from: string | null; valid_to: string | null; is_current: boolean; evidence: EvidenceRef; legal_basis: LegalDocument[]; verification_status: string }
export interface AuthorityDetail { appointment_id: string; person_id: string; public_name: string; position: string; position_type: string; institution: InstitutionRef; capacity: string | null; appointment_status: string; start_date: string | null; end_date: string | null; appointment_act: string | null; appointment_mechanism: string | null; act_located: boolean; appointment_evidence: EvidenceRef[]; current_status_evidence: EvidenceRef[]; verification_level: string; limitations: string[] }
export interface TransparencyComponent { dimension: string; awarded_score: number; maximum_score: number; rule_code: string | null; public_explanation: string; calculation_reason: string; evidence: EvidenceRef; observation_status: string; checked_at: string | null }
export interface TransparencyAssessment { assessment_id: string; assessment_date: string; methodology_version: string; raw_score: number; evaluated_max_score: number; normalized_score: number; coverage_percentage: number; maturity_status: string; rank: null; comparison_position: null; ranking_enabled: false; components: TransparencyComponent[]; public_explanation: string; limitations: string[] }
export interface TransparencyResponse { latest_assessment: TransparencyAssessment | null; historical_assessments: TransparencySummary[]; ranking_enabled: false; limitations: string[] }
export interface InstitutionDetail { id: string; slug: string; official_name: string; short_name: string | null; institution_type: string; status: string; creation_date: string | null; functions_summary: string | null; legal_basis_summary: LegalDocument[]; official_website: string | null; current_authority: AuthorityDetail | null; current_relationships: RelationshipItem[]; official_sources: EvidenceRef[]; evidence: EvidenceRef[]; latest_transparency_assessment: TransparencyAssessment | null; assessment_history: TransparencySummary[]; documentary_gaps: string[]; last_updated_at: string | null; public_limitation: string }
export interface AuthorityListItem { person_id: string; appointment_id: string; public_name: string; position: string; institution: InstitutionRef; appointment_status: string; start_date: string | null; end_date: string | null; appointment_act_status: string; verification_status: string }
export interface PersonAuthorityDetail { person_id: string; public_name: string; positions: string[]; appointments: AuthorityDetail[]; periods: {start_date:string|null;end_date:string|null}[]; evidence: EvidenceRef[]; related_institutions: InstitutionRef[]; limitations: string[] }
export interface ChangeItem { id: string; change_type: string; occurred_at: string; institution: InstitutionRef | null; description: string; evidence: EvidenceRef[] }
