export type SenatorPatrimonySnapshot = {
  senatorId: string;
  declarationPeriod: string;
  declarationUrl: string;
  declarationLinkType: "direct_pdf" | "official_portal" | "official_record";
  reportedAssets?: number;
  reportedLiabilities?: number;
  reportedNetWorth?: number;
  sourceUrl: string;
  sourceLabel: string;
  priorDeclarationId?: string;
  note?: string;
};

const portal = "https://transparencia.senadord.gob.do/declaraciones-juradas-de-patrimonio/";
const dl = "https://flo.uri.sh/visualisation/19660033/embed";
const dlArticle = "https://www.diariolibre.com/politica/gobierno/2024/10/09/entre-politica-y-negocios-las-fortunas-de-los-senadores-dominicanos/2875604";

export const senatorPatrimonyFirst16: Record<string, SenatorPatrimonySnapshot> = {
  "lia-ynocencia-diaz-santana": { senatorId: "lia-ynocencia-diaz-santana", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 46480492.51, reportedLiabilities: 6952503.52, reportedNetWorth: 39527988.99, sourceUrl: "https://diariopuertoplata.com.do/fortuna-de-carlos-gomez-ronda-los-9-9-billones-y-es-mayor-a-la-de-todos-los-senadores-juntos/", sourceLabel: "Datos publicados a partir de Cámara de Cuentas" },
  "andres-guillermo-lama-perez": { senatorId: "andres-guillermo-lama-perez", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 61045383.98, reportedLiabilities: 1, reportedNetWorth: 61045382.98, sourceUrl: dl, sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "moises-ayala-perez": { senatorId: "moises-ayala-perez", declarationPeriod: "2024-08-16", declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43667/moises-ayala-perez.pdf", declarationLinkType: "direct_pdf", reportedAssets: 70077249.89, reportedLiabilities: 16333427.87, reportedNetWorth: 53743822.02, sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43667/moises-ayala-perez.pdf", sourceLabel: "Declaración jurada oficial DJP-42469", priorDeclarationId: "22964" },
  "manuel-maria-rodriguez-ortega": { senatorId: "manuel-maria-rodriguez-ortega", declarationPeriod: "2024-08-16", declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43668/manuel-maria-rodriguez-ortega.pdf", declarationLinkType: "direct_pdf", reportedAssets: 51716557.8, reportedLiabilities: 12562099.21, reportedNetWorth: 39154458.59, sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43668/manuel-maria-rodriguez-ortega.pdf", sourceLabel: "Declaración jurada oficial DJP-42287", priorDeclarationId: "21678" },
  "omar-leonel-fernandez-dominguez": { senatorId: "omar-leonel-fernandez-dominguez", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 13846391.58, reportedLiabilities: 2600000, reportedNetWorth: 11246391.58, sourceUrl: dlArticle, sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "franklin-martin-romero-morillo": { senatorId: "franklin-martin-romero-morillo", declarationPeriod: "2024", declarationUrl: "https://transparencia.senadord.gob.do/wp-content/uploads/wpfd/preview_files/FRANKLIN-MARTIN-ROMERO-MORILLO%28af5f1871fc32857b6d868452b4addac7%29.pdf", declarationLinkType: "direct_pdf", reportedAssets: 471849192.81, sourceUrl: "https://transparencia.senadord.gob.do/wp-content/uploads/wpfd/preview_files/FRANKLIN-MARTIN-ROMERO-MORILLO%28af5f1871fc32857b6d868452b4addac7%29.pdf", sourceLabel: "Declaración jurada oficial DJP-019053" },
  "santiago-jose-zorrilla": { senatorId: "santiago-jose-zorrilla", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 181433093.6, sourceUrl: dl, sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "jonhson-encarnacion-diaz": { senatorId: "jonhson-encarnacion-diaz", declarationPeriod: "2024-08-16", declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43670/jonhson-encarnacion-diaz.pdf", declarationLinkType: "direct_pdf", reportedAssets: 86320279.23, sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43670/jonhson-encarnacion-diaz.pdf", sourceLabel: "Declaración jurada oficial DJP-42652" },
  "carlos-manuel-gomez-urena": { senatorId: "carlos-manuel-gomez-urena", declarationPeriod: "oct. 2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 9942000000, reportedNetWorth: 9940000000, sourceUrl: "https://www.diariolibre.com/amp/politica/general/2025/03/10/carlos-gomez-provincia-espaillat-es-el-senador-mas-adinerado-segun-cc/3028127", sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "cristobal-venerado-castillo-liriano": { senatorId: "cristobal-venerado-castillo-liriano", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 752427719.84, reportedNetWorth: 752427719.84, sourceUrl: dl, sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "maria-mercedes-ortiz-dilone": { senatorId: "maria-mercedes-ortiz-dilone", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 8968923.26, reportedLiabilities: 4200000, reportedNetWorth: 4768923.26, sourceUrl: dlArticle, sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "dagoberto-rodriguez-adames": { senatorId: "dagoberto-rodriguez-adames", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 60513716.41, reportedLiabilities: 27845595.94, reportedNetWorth: 32668120.47, sourceUrl: "https://diariopuertoplata.com.do/fortuna-de-carlos-gomez-ronda-los-9-9-billones-y-es-mayor-a-la-de-todos-los-senadores-juntos/", sourceLabel: "Datos publicados a partir de Cámara de Cuentas" },
  "rafael-baron-duluc-rijo": { senatorId: "rafael-baron-duluc-rijo", declarationPeriod: "2024-08-16", declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43659/rafael-baron-duluc-rijo.pdf", declarationLinkType: "direct_pdf", reportedAssets: 45184045.27, reportedLiabilities: 8761847.39, reportedNetWorth: 36422197.88, sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43659/rafael-baron-duluc-rijo.pdf", sourceLabel: "Declaración jurada oficial DJP-42237", priorDeclarationId: "39472" },
  "eduard-alexis-espiritusanto-castillo": { senatorId: "eduard-alexis-espiritusanto-castillo", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_record", reportedAssets: 986781911.99, reportedLiabilities: 24000000, reportedNetWorth: 962781911.99, sourceUrl: "https://www.camaradecuentas.gob.do/index.php/reportes-djp/category/24-listado-de-funcionarios-que-entregaron-su-declaracion-extemporanea?download=1955%3Aextemporaneas-procuraduria-al-25-10-2024", sourceLabel: "Cámara de Cuentas" },
  "ramon-rogelio-genao-duran": { senatorId: "ramon-rogelio-genao-duran", declarationPeriod: "2024", declarationUrl: portal, declarationLinkType: "official_portal", reportedAssets: 61863531.72, reportedLiabilities: 30025534.46, reportedNetWorth: 31837997.26, sourceUrl: dl, sourceLabel: "Diario Libre · Cámara de Cuentas" },
  "alexis-victoria-yeb": { senatorId: "alexis-victoria-yeb", declarationPeriod: "2024", declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/41290/alexis-victoria-yeb.pdf", declarationLinkType: "direct_pdf", reportedAssets: 3928019156.42, reportedLiabilities: 237187634.36, reportedNetWorth: 3690831522.06, sourceUrl: dlArticle, sourceLabel: "Diario Libre · declaración oficial Cámara de Cuentas" }
};

export const first16PatrimonyIds = Object.keys(senatorPatrimonyFirst16);
