import type { SenatorPatrimonySnapshot } from "@/lib/senator-patrimony-first16";

const senateDeclarationPortal =
  "https://transparencia.senadord.gob.do/declaraciones-juradas-de-patrimonio/";

const dlPatrimony = "https://flo.uri.sh/visualisation/19660033/embed";
const dlPatrimonyArticle =
  "https://www.diariolibre.com/politica/gobierno/2024/10/09/entre-politica-y-negocios-las-fortunas-de-los-senadores-dominicanos/2875604";
const dlEpaper =
  "https://epaper.diariolibre.com/epaper/xml_epaper/diariolibre/10_10_2024/pla_482_General/pdf_pags/482.pdf?t=1296432000";

/**
 * Segunda ola patrimonial: senadores 17-32 del roster 2024-2028.
 * Los valores de "Total" del consolidado Diario Libre/Camara de Cuentas se
 * conservan como activos/total publicado, salvo que la fuente publique de
 * forma explicita patrimonio neto y/o pasivos.
 */
export const senatorPatrimonySecond16: Record<string, SenatorPatrimonySnapshot> = {
  "hector-elpidio-acosta-restituyo": {
    senatorId: "hector-elpidio-acosta-restituyo",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 82222701.52,
    reportedLiabilities: 15612303.64,
    reportedNetWorth: 66610397.88,
    sourceUrl: dlEpaper,
    sourceLabel: "Diario Libre · consolidado de declaraciones publicadas por Cámara de Cuentas",
    note: "Reelecto. El OED buscará su declaración 2020 compatible para medir la evolución patrimonial con la misma metodología.",
  },
  "bernardo-aleman-rodriguez": {
    senatorId: "bernardo-aleman-rodriguez",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    sourceUrl: senateDeclarationPortal,
    sourceLabel: "Portal oficial de declaraciones juradas del Senado",
    note: "El OED todavía no ha resuelto un consolidado patrimonial individual suficientemente verificable para publicar una cifra. Se mantiene enlazado el portal oficial sin inventar monto ni PDF.",
  },
  "pedro-antonio-tineo-nunez": {
    senatorId: "pedro-antonio-tineo-nunez",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 62944535.34,
    sourceUrl: dlPatrimony,
    sourceLabel: "Visualización de declaraciones juradas basada en Cámara de Cuentas · Diario Libre",
    note: "La visualización publica RD$62,944,535.34 como total declarado. El OED no lo presenta como patrimonio neto hasta resolver pasivos y PDF individual.",
  },
  "secundino-velazquez-pimentel": {
    senatorId: "secundino-velazquez-pimentel",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_record",
    reportedAssets: 153350526.02,
    reportedLiabilities: 2311988.87,
    reportedNetWorth: 151038537.15,
    sourceUrl: dlEpaper,
    sourceLabel: "Diario Libre · consolidado de declaraciones publicadas por Cámara de Cuentas",
    note: "La Cámara de Cuentas lo incluye entre las declaraciones presentadas en 2024; queda pendiente resolver el PDF individual exacto.",
  },
  "julito-fulcar-encarnacion": {
    senatorId: "julito-fulcar-encarnacion",
    declarationPeriod: "2024-08-16",
    declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43661/julito-fulcar-encarnacion.pdf",
    declarationLinkType: "direct_pdf",
    reportedNetWorth: 27472119,
    sourceUrl: "https://noticiassin.com/de-la-camara-de-diputados-al-senado-julito-furcal-presenta-patrimonio-de-rd27-5-mm/",
    sourceLabel: "Noticias SIN · cálculo corregido a partir de declaración jurada",
    priorDeclarationId: "22723",
    note: "La publicación corrigió su cálculo y fijó el patrimonio total en RD$27,472,119. La declaración vigente identifica una declaración anterior, útil para reconstruir 2020→2024.",
  },
  "ginnette-altagracia-bournigal": {
    senatorId: "ginnette-altagracia-bournigal",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 20411803.95,
    sourceUrl: dlPatrimony,
    sourceLabel: "Visualización de declaraciones juradas basada en Cámara de Cuentas · Diario Libre",
    note: "Reelecta. El total publicado se conserva como total/activos declarados hasta resolver pasivos y la declaración anterior comparable.",
  },
  "pedro-manuel-catrain-bonilla": {
    senatorId: "pedro-manuel-catrain-bonilla",
    declarationPeriod: "2024",
    declarationUrl: "https://www.transparencia.senadord.gob.do/wp-content/uploads/wpfd/preview_files/PEDRO-MANUEL-CATRAIN-BONILLA%28443ecbd48bc81e881b05d044e4376b6f%29.pdf",
    declarationLinkType: "direct_pdf",
    reportedNetWorth: 188255877.86,
    sourceUrl: dlEpaper,
    sourceLabel: "Diario Libre · consolidado corregido de declaración Cámara de Cuentas",
    note: "El cuadro publicado identifica RD$188,255,877.86 como patrimonio neto tras corregir el tratamiento de un vehículo expresado en dólares. El OED no mezcla automáticamente monedas.",
  },
  "gustavo-lara-salazar": {
    senatorId: "gustavo-lara-salazar",
    declarationPeriod: "2024-08-16",
    declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43663/gustavo-lara-salazar.pdf",
    declarationLinkType: "direct_pdf",
    reportedAssets: 14455079.36,
    reportedLiabilities: 10300000,
    reportedNetWorth: 4155079.36,
    sourceUrl: dlPatrimonyArticle,
    sourceLabel: "Diario Libre · análisis de declaración jurada Cámara de Cuentas",
    priorDeclarationId: "25086",
    note: "La fuente reporta aproximadamente RD$10.3 millones en pasivos y RD$4.1 millones netos. La declaración DJP-42676 identifica una declaración anterior ID 25086.",
  },
  "milciades-aneudy-ortiz-sajiun": {
    senatorId: "milciades-aneudy-ortiz-sajiun",
    declarationPeriod: "2024-08-16",
    declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43672/milciades-aneudy-ortiz-sajiun.pdf",
    declarationLinkType: "direct_pdf",
    reportedAssets: 26895187.26,
    sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43672/milciades-aneudy-ortiz-sajiun.pdf",
    sourceLabel: "Declaración jurada oficial DJP-42324",
    priorDeclarationId: "19335",
    note: "Actualización por cambio de cargo. El formulario identifica como declaración anterior una actualización ID 19335. El total publicado por el consolidado 2024 es RD$26,895,187.26.",
  },
  "felix-ramon-bautista-rosario": {
    senatorId: "felix-ramon-bautista-rosario",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 213517382.38,
    reportedLiabilities: 10324921.24,
    reportedNetWorth: 203192461.14,
    sourceUrl: dlEpaper,
    sourceLabel: "Diario Libre · consolidado de declaraciones publicadas por Cámara de Cuentas",
    note: "Reelecto. El OED mostrará evolución histórica solo cuando las declaraciones anteriores estén normalizadas con la misma semántica de activos y pasivos.",
  },
  "aracelis-villanueva-figueroa": {
    senatorId: "aracelis-villanueva-figueroa",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 9741939.87,
    sourceUrl: dlPatrimony,
    sourceLabel: "Visualización de declaraciones juradas basada en Cámara de Cuentas · Diario Libre",
    note: "El consolidado publica RD$9,741,939.87 como total declarado. El patrimonio neto permanece pendiente hasta resolver pasivos y PDF individual.",
  },
  "ricardo-de-los-santos-polanco": {
    senatorId: "ricardo-de-los-santos-polanco",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 53751195.49,
    sourceUrl: dlPatrimony,
    sourceLabel: "Visualización de declaraciones juradas basada en Cámara de Cuentas · Diario Libre",
    note: "Reelecto. El total 2024 se conserva separado de patrimonio neto hasta resolver pasivos; se buscará además la declaración 2020 para evolución histórica.",
  },
  "daniel-enrique-rivera-reyes": {
    senatorId: "daniel-enrique-rivera-reyes",
    declarationPeriod: "2024-08-16",
    declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43664/daniel-enrique-de-jesus-rivera-reyes.pdf",
    declarationLinkType: "direct_pdf",
    reportedAssets: 41838542.84,
    sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43664/daniel-enrique-de-jesus-rivera-reyes.pdf",
    sourceLabel: "Declaración jurada oficial DJP-41346",
    priorDeclarationId: "30193",
    note: "Actualización por cambio de cargo al Senado. El formulario identifica una declaración anterior rectificativa ID 30193.",
  },
  "casimiro-antonio-marte-familia": {
    senatorId: "casimiro-antonio-marte-familia",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 70396212.44,
    reportedLiabilities: 4448981.03,
    reportedNetWorth: 65947231.41,
    sourceUrl: dlEpaper,
    sourceLabel: "Diario Libre · consolidado de declaraciones publicadas por Cámara de Cuentas",
    note: "Reelecto. El OED buscará la declaración anterior compatible para medir evolución patrimonial.",
  },
  "antonio-manuel-taveras-guzman": {
    senatorId: "antonio-manuel-taveras-guzman",
    declarationPeriod: "2024",
    declarationUrl: senateDeclarationPortal,
    declarationLinkType: "official_portal",
    reportedAssets: 1009275617.26,
    reportedLiabilities: 572293779.37,
    reportedNetWorth: 436981837.89,
    sourceUrl: dlPatrimonyArticle,
    sourceLabel: "Diario Libre · análisis de declaración jurada Cámara de Cuentas",
    note: "La fuente reporta RD$1,009.3 millones en activos y RD$572.2 millones en pasivos, mayormente préstamos. Reelecto; queda pendiente normalizar su declaración 2020 para evolución.",
  },
  "odalis-rafael-rodriguez-rodriguez": {
    senatorId: "odalis-rafael-rodriguez-rodriguez",
    declarationPeriod: "2024-08-16",
    declarationUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43675/odalis-rafael-rodriguez-rodriguez.pdf",
    declarationLinkType: "direct_pdf",
    reportedAssets: 34103800.24,
    sourceUrl: "https://transparencia.senadord.gob.do/download/187/declaraciones-juradas/43675/odalis-rafael-rodriguez-rodriguez.pdf",
    sourceLabel: "Declaración jurada oficial DJP-42196",
    note: "Declaración del período vigente. El total publicado en el consolidado 2024 es RD$34,103,800.24; el patrimonio neto queda pendiente de recálculo completo del formulario.",
  },
};

export const second16PatrimonyIds = Object.keys(senatorPatrimonySecond16);
