export type VerifiedSenatorAttendance = {
  period: string;
  plenarySessions?: number;
  attended?: number;
  excused?: number;
  unjustifiedAbsences?: number;
  presenceRate: number;
  excusedRate: number;
  absenceRate: number;
  sourceUrl: string;
  sourceLabel: string;
  methodologyNote?: string;
};

/**
 * Attendance is published only when the OED has an identifiable source based
 * on Senate attendance records that provides a complete count or explicit
 * percentages. Excused absences are kept separate from unjustified absences.
 */
export const verifiedSenatorAttendance: Record<string, VerifiedSenatorAttendance[]> = {
  "lia-ynocencia-diaz-santana": [
    {
      period: "16 ago. 2025 – 12 ene. 2026",
      plenarySessions: 24,
      attended: 24,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/02/06/legisladores-registran-altas-cifras-de-ausencia-a-sesiones/3427897",
      sourceLabel: "Diario Libre · revisión de actas y resúmenes oficiales del Senado",
      methodologyNote: "Asistencia perfecta en las 24 sesiones del período.",
    },
  ],
  "andres-guillermo-lama-perez": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Asistencia perfecta en las 26 sesiones revisadas.",
    },
  ],
  "omar-leonel-fernandez-dominguez": [
    {
      period: "16 ago. 2024 – 12 ene. 2025",
      plenarySessions: 24,
      attended: 17,
      excused: 7,
      unjustifiedAbsences: 0,
      presenceRate: 70.8,
      excusedRate: 29.2,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2025/01/27/conozca-a-los-senadores-ausentes-de-las-sesiones/2979560",
      sourceLabel: "Diario Libre · revisión de registros semanales y actas oficiales del Senado",
      methodologyNote: "Siete faltas en 24 sesiones, todas registradas con excusa; 17 presencias calculadas por diferencia.",
    },
  ],
  "franklin-martin-romero-morillo": [
    {
      period: "16 ago. 2024 – 12 ene. 2025",
      plenarySessions: 24,
      attended: 15,
      excused: 9,
      unjustifiedAbsences: 0,
      presenceRate: 62.5,
      excusedRate: 37.5,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2025/01/27/conozca-a-los-senadores-ausentes-de-las-sesiones/2979560",
      sourceLabel: "Diario Libre · revisión de registros semanales y actas oficiales del Senado",
      methodologyNote: "Nueve faltas en 24 sesiones, todas registradas con excusa; 15 presencias calculadas por diferencia.",
    },
  ],
  "maria-mercedes-ortiz-dilone": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Asistencia perfecta en las 26 sesiones revisadas.",
    },
  ],
  "dagoberto-rodriguez-adames": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Asistencia perfecta en las 26 sesiones revisadas.",
    },
  ],
  "eduard-alexis-espiritusanto-castillo": [
    {
      period: "16 ago. 2024 – 12 ene. 2025",
      plenarySessions: 24,
      attended: 18,
      excused: 6,
      unjustifiedAbsences: 0,
      presenceRate: 75,
      excusedRate: 25,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2025/01/27/conozca-a-los-senadores-ausentes-de-las-sesiones/2979560",
      sourceLabel: "Diario Libre · revisión de registros semanales y actas oficiales del Senado",
      methodologyNote: "Seis faltas en 24 sesiones, todas registradas con excusa; 18 presencias calculadas por diferencia.",
    },
  ],
  "hector-elpidio-acosta-restituyo": [
    {
      period: "16 ago. 2025 – 12 ene. 2026",
      plenarySessions: 24,
      attended: 8,
      excused: 16,
      unjustifiedAbsences: 0,
      presenceRate: 33.3,
      excusedRate: 66.7,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/02/06/legisladores-registran-altas-cifras-de-ausencia-a-sesiones/3427897",
      sourceLabel: "Diario Libre · revisión de actas y resúmenes oficiales del Senado",
      methodologyNote: "16 ausencias de 24 sesiones, todas con excusa. La fuente señala una situación de salud que el senador hizo pública.",
    },
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 16,
      excused: 10,
      unjustifiedAbsences: 0,
      presenceRate: 61.5,
      excusedRate: 38.5,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Diez de las 26 sesiones figuran con excusa; ninguna ausencia fue registrada como injustificada.",
    },
  ],
  "bernardo-aleman-rodriguez": [
    {
      period: "16 ago. 2025 – 12 ene. 2026",
      plenarySessions: 24,
      attended: 14,
      excused: 10,
      unjustifiedAbsences: 0,
      presenceRate: 58.3,
      excusedRate: 41.7,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/02/06/legisladores-registran-altas-cifras-de-ausencia-a-sesiones/3427897",
      sourceLabel: "Diario Libre · revisión de actas y resúmenes oficiales del Senado",
      methodologyNote: "Diez faltas de 24 sesiones, todas con excusa; 14 presencias calculadas por diferencia.",
    },
  ],
  "pedro-antonio-tineo-nunez": [
    {
      period: "16 ago. 2024 – 12 ene. 2025",
      plenarySessions: 24,
      attended: 15,
      excused: 9,
      unjustifiedAbsences: 0,
      presenceRate: 62.5,
      excusedRate: 37.5,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2025/01/27/conozca-a-los-senadores-ausentes-de-las-sesiones/2979560",
      sourceLabel: "Diario Libre · revisión de registros semanales y actas oficiales del Senado",
      methodologyNote: "Nueve faltas en 24 sesiones, todas registradas con excusa; 15 presencias calculadas por diferencia.",
    },
  ],
  "secundino-velazquez-pimentel": [
    {
      period: "2024-2025",
      plenarySessions: 67,
      attended: 61,
      excused: 6,
      unjustifiedAbsences: 0,
      presenceRate: 91,
      excusedRate: 9,
      absenceRate: 0,
      sourceUrl: "https://cdnc.heyzine.com/files/uploaded/v3/dde740efa9deac1b2f6a844dca68328a4226b74e.pdf",
      sourceLabel: "Informe de Gestión Senatorial Pedernales 2024-2025 · Departamento Elaboración de Actas",
      methodologyNote: "El informe consolida 67 sesiones/actas, 61 presencias, 6 excusas y 0 ausencias.",
    },
  ],
  "julito-fulcar-encarnacion": [
    {
      period: "2024-2025",
      presenceRate: 96,
      excusedRate: 4,
      absenceRate: 0,
      sourceUrl: "https://fliphtml5.com/qintr/wqwa/web-memoriasJulito-new/",
      sourceLabel: "Informe de Gestión Social y Legislativa 2024-2025 · Senador Julito Fulcar",
      methodologyNote: "El informe publica directamente los porcentajes de presencia, excusas y ausencias.",
    },
  ],
  "ginnette-altagracia-bournigal": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 18,
      excused: 8,
      unjustifiedAbsences: 0,
      presenceRate: 69.2,
      excusedRate: 30.8,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Ocho de las 26 sesiones figuran con excusa; ninguna ausencia fue registrada como injustificada.",
    },
  ],
  "felix-ramon-bautista-rosario": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 15,
      excused: 11,
      unjustifiedAbsences: 0,
      presenceRate: 57.7,
      excusedRate: 42.3,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Once de las 26 sesiones figuran con excusa; ninguna ausencia fue registrada como injustificada.",
    },
  ],
  "ricardo-de-los-santos-polanco": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Asistencia perfecta en las 26 sesiones revisadas.",
    },
  ],
  "daniel-enrique-rivera-reyes": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Asistencia perfecta en las 26 sesiones revisadas.",
    },
  ],
  "casimiro-antonio-marte-familia": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "La fuente lo identifica como Antonio Marte, correspondiente a Casimiro Antonio Marte Familia. Asistencia perfecta en las 26 sesiones.",
    },
  ],
  "odalis-rafael-rodriguez-rodriguez": [
    {
      period: "27 feb. – 26 jul. 2026",
      plenarySessions: 26,
      attended: 26,
      excused: 0,
      unjustifiedAbsences: 0,
      presenceRate: 100,
      excusedRate: 0,
      absenceRate: 0,
      sourceUrl: "https://www.diariolibre.com/politica/congreso-nacional/2026/08/12/los-senadores-se-escudaron-en-100-excusas-para-faltar-a-las-sesiones/3626113",
      sourceLabel: "Diario Libre · revisión de las 26 actas del Senado",
      methodologyNote: "Asistencia perfecta en las 26 sesiones revisadas.",
    },
  ],
};
