import type { Legislator } from "@/lib/legislators";

export const senatorProfileUrls: Record<string, string> = {
  "lia-ynocencia-diaz-santana": "https://www.senadord.gob.do/provincia/azua/",
  "andres-guillermo-lama-perez": "https://www.senadord.gob.do/provincia/bahoruco/",
  "moises-ayala-perez": "https://www.senadord.gob.do/provincia/barahona/",
  "manuel-maria-rodriguez-ortega": "https://www.senadord.gob.do/provincia/dajabon/",
  "omar-leonel-fernandez-dominguez": "https://www.senadord.gob.do/provincia/distrito-nacional/",
  "franklin-martin-romero-morillo": "https://www.senadord.gob.do/provincia/duarte/",
  "santiago-jose-zorrilla": "https://www.senadord.gob.do/provincia/el-seibo/",
  "jonhson-encarnacion-diaz": "https://www.senadord.gob.do/provincia/elias-pina/",
  "carlos-manuel-gomez-urena": "https://www.senadord.gob.do/provincia/espaillat/",
  "cristobal-venerado-castillo-liriano": "https://www.senadord.gob.do/provincia/hato-mayor/",
  "maria-mercedes-ortiz-dilone": "https://www.senadord.gob.do/provincia/hermanas-mirabal/",
  "dagoberto-rodriguez-adames": "https://www.senadord.gob.do/provincia/independencia/",
  "rafael-baron-duluc-rijo": "https://www.senadord.gob.do/provincia/la-altagracia/",
  "eduard-alexis-espiritusanto-castillo": "https://www.senadord.gob.do/provincia/la-romana/",
  "ramon-rogelio-genao-duran": "https://www.senadord.gob.do/provincia/la-vega/",
  "alexis-victoria-yeb": "https://www.senadord.gob.do/provincia/maria-trinidad-sanchez/",
  "hector-elpidio-acosta-restituyo": "https://www.senadord.gob.do/provincia/monsenor-nouel/",
  "bernardo-aleman-rodriguez": "https://www.senadord.gob.do/provincia/montecristi/",
  "pedro-antonio-tineo-nunez": "https://www.senadord.gob.do/provincia/monte-plata/",
  "secundino-velazquez-pimentel": "https://www.senadord.gob.do/provincia/pedernales/",
  "julito-fulcar-encarnacion": "https://www.senadord.gob.do/provincia/peravia/",
  "ginnette-altagracia-bournigal": "https://www.senadord.gob.do/provincia/puerto-plata/",
  "pedro-manuel-catrain-bonilla": "https://www.senadord.gob.do/provincia/samana/",
  "gustavo-lara-salazar": "https://www.senadord.gob.do/provincia/san-cristobal/",
  "milciades-aneudy-ortiz-sajiun": "https://www.senadord.gob.do/provincia/san-jose-de-ocoa/",
  "felix-ramon-bautista-rosario": "https://www.senadord.gob.do/provincia/san-juan/",
  "aracelis-villanueva-figueroa": "https://www.senadord.gob.do/provincia/san-pedro-de-macoris/",
  "ricardo-de-los-santos-polanco": "https://www.senadord.gob.do/provincia/sanchez-ramirez/",
  "daniel-enrique-rivera-reyes": "https://www.senadord.gob.do/provincia/santiago/",
  "casimiro-antonio-marte-familia": "https://www.senadord.gob.do/provincia/santiago-rodriguez/",
  "antonio-manuel-taveras-guzman": "https://www.senadord.gob.do/provincia/santo-domingo/",
  "odalis-rafael-rodriguez-rodriguez": "https://www.senadord.gob.do/provincia/valverde/",
};

export const senatorCompletion: Record<string, Partial<Legislator>> = {
  "secundino-velazquez-pimentel": {
    officialProfileUrl: senatorProfileUrls["secundino-velazquez-pimentel"],
    educationStatus: "verified",
    education: [
      {
        level: "primaria",
        credential: "Estudios primarios",
        institution: "Comunidad de Aguas Negras, hoy Distrito José Francisco Peña Gómez",
        status: "completed",
        sourceUrl: senatorProfileUrls["secundino-velazquez-pimentel"],
      },
      {
        level: "secundaria",
        credential: "Estudios secundarios",
        institution: "Liceo de Pedernales",
        status: "completed",
        sourceUrl: senatorProfileUrls["secundino-velazquez-pimentel"],
      },
      {
        level: "grado",
        credential: "Ingeniero Civil",
        institution: "Instituto Tecnológico de Santo Domingo (INTEC)",
        status: "completed",
        sourceUrl: senatorProfileUrls["secundino-velazquez-pimentel"],
      },
    ],
    educationNote: "El perfil oficial indica que obtuvo el título de Ingeniería Civil en 2004.",
  },
  "casimiro-antonio-marte-familia": {
    officialProfileUrl: senatorProfileUrls["casimiro-antonio-marte-familia"],
    educationStatus: "not_found",
    education: [],
    educationNote:
      "El perfil oficial del Senado documenta su trayectoria empresarial, sindical, participación en organismos internacionales y asistencia a congresos y seminarios, pero no publica un grado, título o institución académica verificable.",
  },
  "antonio-manuel-taveras-guzman": {
    officialProfileUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
    educationStatus: "verified",
    education: [
      {
        level: "estudios universitarios",
        credential: "Estudios de Sociología",
        institution: "Universidad Autónoma de Santo Domingo (UASD)",
        status: "completed",
        sourceUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
      },
      {
        level: "grado",
        credential: "Derecho",
        institution: "Universidad de la Tercera Edad (UTE)",
        status: "completed",
        sourceUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
      },
      {
        level: "postgrado",
        credential: "Derecho Civil",
        institution: "Universidad Autónoma de Santo Domingo (UASD)",
        status: "completed",
        sourceUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
      },
      {
        level: "maestría",
        credential: "Máster en Ciencias Políticas para el Desarrollo",
        institution: "Universidad de Salamanca, España",
        status: "completed",
        sourceUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
      },
      {
        level: "formación especializada",
        credential: "Geopolítica y Negocios Internacionales",
        institution: "Instituto Global de Altos Estudios en Ciencias Sociales (IGLOBAL)",
        status: "completed",
        sourceUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
      },
      {
        level: "maestría",
        credential: "Máster en Alta Dirección de Empresas",
        institution: "Barna Management School",
        status: "completed",
        sourceUrl: senatorProfileUrls["antonio-manuel-taveras-guzman"],
      },
    ],
  },
  "odalis-rafael-rodriguez-rodriguez": {
    officialProfileUrl: senatorProfileUrls["odalis-rafael-rodriguez-rodriguez"],
    educationStatus: "verified",
    education: [
      {
        level: "primaria",
        credential: "Estudios primarios",
        institution: "Escuela Juan Isidro Pérez, Mao",
        status: "completed",
        sourceUrl: senatorProfileUrls["odalis-rafael-rodriguez-rodriguez"],
      },
      {
        level: "secundaria",
        credential: "Estudios secundarios",
        institution: "Liceo Santa Cruz y Liceo Secundario Prof. Juan de Js. Reyes Aranda",
        status: "completed",
        sourceUrl: senatorProfileUrls["odalis-rafael-rodriguez-rodriguez"],
      },
      {
        level: "grado",
        credential: "Doctor en Medicina",
        institution: "Universidad Autónoma de Santo Domingo (UASD)",
        status: "completed",
        sourceUrl: senatorProfileUrls["odalis-rafael-rodriguez-rodriguez"],
      },
      {
        level: "especialidad",
        credential: "Pediatría y Puericultura",
        institution: "Hospital San Carlos / Universidad Complutense de Madrid, España",
        status: "completed",
        sourceUrl: senatorProfileUrls["odalis-rafael-rodriguez-rodriguez"],
      },
    ],
    educationNote: "El perfil oficial sitúa la especialidad entre 1983 y 1986.",
  },
};
